dist:
	mkdir dist
	python setup.py dist

clean:
	rm maay/*.pyc
	rm maay/converter/*.pyc
	rm maay/win32/*.pyc
	rm maay/linux/*.pyc
	rm maay/config/*.pyc
	rm maay/datastructure/*.pyc
	rm -rf build/
	rm -rf dist/
	rm -rf testenv/

# TODO
deb:	clean
rpm:	clean
